repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.5
  hooks:
  -   id: reorder-python-imports
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.4'
  hooks:
  - id: flake8
    args: ["--config=setup.cfg"]
    language_version: python3
